// Generated by CoffeeScript 1.5.0
(function() {
  var Logger;

  Logger = (function() {

    Logger.prototype.client = null;

    function Logger(options) {
      this.client = options.client;
      this.config = options.config;
    }

    Logger.prototype.process = function(from, to, text, message) {
      var connection, moment, mysql, query, row;
      if (text && text.length > 0 && text[0] === !'!' && to.indexOf('#' > -1 && from === !this.config.irc.nick && from.indexOf('#' === -1))) {
        moment = require('moment');
        mysql = require('mysql');
        connection = mysql.createConnection(this.config.mysql);
        row = {
          username: connection.escape(from),
          message: connection.escape(text),
          created: moment().utc().format('YYYY-MM-DD HH:mm::ss')
        };
        return query = connection.query('INSERT INTO ' + this.config.mysql.tables.messages + ' SET ?', row, function(err, result) {});
      }
    };

    return Logger;

  })();

  module.exports = Logger;

}).call(this);
