// Generated by CoffeeScript 1.5.0
(function() {
  var Actions, Logger, actions, client, config, http, irc, logger, server;

  config = require('../config');

  irc = require('irc');

  client = new ircClient(config.irc.server, config.irc.nick, config.irc.options);

  Actions = require('./processors/actions');

  actions = new Actions(client);

  Logger = require('./processors/logger');

  logger = new Logger(client);

  client.addListener('message', function(from, to, text, message) {
    actions.process(from, to, text, message);
    return logger.process(from, to, text, message);
  });

  if (config.server) {
    http = require('http');
    server = http.createServer(function(req, res) {
      res.writeHead(200, {
        'Content-type': 'text/html'
      });
      return res.end('Hello from CroogoBot!');
    });
    server.listen(process.env.VMC_APP_PORT || 1337, null);
  }

}).call(this);
