// Generated by CoffeeScript 1.5.0
(function() {
  var Bot;

  Bot = (function() {

    function Bot(options) {
      this.config = options.config;
    }

    Bot.prototype.run = function() {
      var Actions, Logger, actions, client, http, irc, logger, server;
      irc = require('irc');
      client = new irc.Client(this.config.irc.server, this.config.irc.nick, this.config.irc.options);
      Actions = require('./processors/actions');
      actions = new Actions({
        client: client,
        config: this.config
      });
      Logger = require('./processors/logger');
      logger = new Logger({
        client: client,
        config: this.config
      });
      client.addListener('message', function(from, to, text, message) {
        actions.process(from, to, text, message);
        return logger.process(from, to, text, message);
      });
      if (this.config.server) {
        http = require('http');
        server = http.createServer(function(req, res) {
          res.writeHead(200, {
            'Content-type': 'text/html'
          });
          return res.end('Hello from CroogoBot!');
        });
        return server.listen(process.env.VMC_APP_PORT || 1337, null);
      }
    };

    return Bot;

  })();

  module.exports = Bot;

}).call(this);
