// Generated by CoffeeScript 1.5.0
(function() {
  var action;

  action = function(from, to, text, messsage) {
    var q;
    q = text.split(/\ (.+)/)[1];
    if (!q || q.length === 0) {
      return 'no ID given';
    }
    return 'http://croogo.lighthouseapp.com/projects/32818/tickets/' + escape(q);
  };

  module.exports = action;

}).call(this);
